// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umjxurkhtrqvuiraoggl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtanh1cmtodHJxdnVpcmFvZ2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjgxNDQsImV4cCI6MjA2NTg0NDE0NH0.6FNfaJY91s1pUHHOcBU8CwCTSGlBTGI_OR3KYKRKEvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);